package app.entities;
// Generated May 22, 2020 12:15:34 PM by Hibernate Tools 5.2.12.Final

import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "gestion_ecole")
public class User implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String nom;
	private String prenom;
	private String login;
	private String password;
	private String theme;
	private Date lastLogin;
	private Set<Etudiant> etudiants = new HashSet<Etudiant>(0);
	private Set<Filiere> filieres = new HashSet<Filiere>(0);
	
	public User() {
	}

	public User(String nom, String prenom, String login, String password, String theme, Date lastLogin) {
		this.nom = nom;
		this.prenom = prenom;
		this.login = login;
		this.password = password;
		this.theme = theme;
		this.lastLogin = lastLogin;
	}

	public User(String nom, String prenom, String login, String password, String theme, Date lastLogin,
			Set<Etudiant> etudiants, Set<Filiere> filieres) {
		this.nom = nom;
		this.prenom = prenom;
		this.login = login;
		this.password = password;
		this.theme = theme;
		this.lastLogin = lastLogin;
		this.etudiants = etudiants;
		this.filieres = filieres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nom", nullable = false)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", nullable = false)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "login", nullable = false)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}
	
	public String md5(String txt) throws UnsupportedEncodingException, NoSuchAlgorithmException  {
		 MessageDigest md = MessageDigest.getInstance("MD5"); 
         byte[] messageDigest = md.digest(txt.getBytes()); 
         BigInteger no = new BigInteger(1, messageDigest); 
         String hashtext = no.toString(16); 
         while (hashtext.length() < 32) {
             hashtext = "0" + hashtext; 
         }
		return hashtext;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "theme", nullable = false)
	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_login", nullable = true, length = 19)
	public Date getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Etudiant> getEtudiants() {
		return this.etudiants;
	}

	public void setEtudiants(Set<Etudiant> etudiants) {
		this.etudiants = etudiants;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Filiere> getFilieres() {
		return this.filieres;
	}

	public void setFilieres(Set<Filiere> filieres) {
		this.filieres = filieres;
	}

}
